version: 1.0.{build}
os: Visual Studio 2015 CTP

install: 
  - ps: Start-FileDownload https://raw.githubusercontent.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1
  - ps: Import-Module './vsix.ps1'

before_build: 
  - ps: Vsix-IncrementVsixVersion -updateBuildVersion

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_build:
  - ps: Vsix-PushArtifacts -publishToGallery