// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.GlyphExporter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGlyphExporterPkgString = "c1e1a7aa-d416-4600-81ce-a0aba0a3b201";
        public const string guidGlyphExporterCmdSetString = "3fc922ee-7ea1-456e-86df-f5a5ad462cdc";
        public static Guid guidGlyphExporterPkg = new Guid(guidGlyphExporterPkgString);
        public static Guid guidGlyphExporterCmdSet = new Guid(guidGlyphExporterCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidGlyph = 0x0100;
    }
}
