// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.GlyphExporter
{
    static class Vsix
    {
        public const string Id = "c1e1a7aa-d416-4600-81ce-a0aba0a3b201";
        public const string Name = "Glyph Exporter";
        public const string Description = @"Exports all glyph icons to image files";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
